/*
  Warnings:

  - You are about to drop the `Book` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Book";

-- CreateTable
CREATE TABLE "Books" (
    "bookId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "authorName" STRING NOT NULL,
    "authorLastName" STRING NOT NULL,
    "pages" INT4 NOT NULL,
    "publisher" STRING NOT NULL,
    "publishYear" INT4 NOT NULL,
    "review" STRING NOT NULL,
    "cover" STRING NOT NULL,
    "status" "Status" NOT NULL,

    CONSTRAINT "Books_pkey" PRIMARY KEY ("bookId")
);
