-- AlterSequence
ALTER SEQUENCE "Books_bookId_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "Books" ALTER COLUMN "review" DROP NOT NULL;
ALTER TABLE "Books" ALTER COLUMN "status" DROP NOT NULL;
ALTER TABLE "Books" ALTER COLUMN "status" SET DEFAULT 'PENDING';
